# fly.toml app configuration file generated for jetsetradio-api-admin on 2023-10-12T11:34:39-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "jetsetradio-api-admin"
primary_region = "dfw"

[build]
  builder = "heroku/buildpacks:20"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true

[checks]
  [checks.alive]
    type = "tcp"
    interval = "15s"
    timeout = "2s"
    grace_period = "5s"
